### ISSUE TITLE
Wabbajack Installation Failed

### ISSUE THREAD

**Issue by Artimidorus** [LeArby/OpenMW-Enhanced#15]
Here is the last part of the installation log. This is my second attempt.
For some reason it cant download https://github.com/LeArby/OpenMW-Enhanced/releases/download/OPENMW-Essentials/OpenMW.Enhanced.Essentials.zip and when I manually downloaded it and added it to the downloads folder. It doesn't see it.

00:36:31.577 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:36:31.577 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:36:31.577 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:36:31.591 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: OpenMW Enhanced - 0.0.1.0
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: D:\Program Files (x86)\Bethesda Softworks\Mod
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: D:\Program Files (x86)\Bethesda Softworks\Downloads
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: F:\SteamLibrary\steamapps\common\Morrowind
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: D:\Program Files (x86)\Bethesda Softworks\3.2.0.1
00:36:31.761 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:36:31.990 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:36:31.990 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:36:32.082 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:36:32.082 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:36:32.082 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 69026 directives to 69026 required
00:36:32.102 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:36:32.102 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:36:32.114 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:36:32.130 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:36:32.141 [INFO] (Wabbajack.Installer.StandardInstaller) Found 7671 total files, 229953 matching filesize
00:36:45.413 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
00:36:45.413 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:36:45.574 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:36:45.574 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:36:45.574 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
00:36:45.574 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:36:45.574 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading OpenMW.Enhanced.Essentials.zip
00:36:45.574 [DEBUG] (Wabbajack.Networking.Http.SingleThreadedDownloader) Download for 'OpenMW.Enhanced.Essentials_0c3c833ad135963a3a09820779877d7a9c2efdefb6c087ad7d4582d62e4d7f8c_.zip' is starting from scratch...
00:36:47.727 [INFO] (Wabbajack.Downloaders.DownloadDispatcher) Finished downloading OpenMW.Enhanced.Essentials.zip. Hash: 5FTtTf5H+EQ=; Size: 7.5MB/7.5MB
00:36:47.892 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for BVtdkeaj8uA=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 119
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 57
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 245
00:36:47.892 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: BVtdkeaj8uA=
00:36:47.892 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:36:47.892 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:36:47.917 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:36:47.935 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:36:47.942 [INFO] (Wabbajack.Installer.StandardInstaller) Found 7671 total files, 229953 matching filesize
00:37:00.004 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download OpenMW.Enhanced.Essentials.zip (HTTPDownloader+State|https://github.com/LeArby/OpenMW-Enhanced/releases/download/OPENMW-Essentials/OpenMW.Enhanced.Essentials.zip)
00:37:00.004 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by bradleymarques** [comment]
Same.
